WebProgramming/mixr/config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :modifications
  resources :votes
  resources :subscribers

  get 'search', to: 'search#search'
  get 'welcome/index'
  root 'welcome#index'
end

WebProgramming/mixr/app/models/recipe.rb
class Recipe 
  include Mongoid::Document
  include Mongoid::Paperclip
  field :title, type: String

  has_many :subscribers
  has_many :recipe_ingredients, dependent: :delete
  has_many :steps, dependent: :delete
  has_many :votes, as: :rateable

  validates :title, presence: true, length: { minimum: 2, maximum: 255 }

  accepts_nested_attributes_for :recipe_ingredients, :steps

  has_mongoid_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_size :image, :less_than => (0.05).megabytes, 
                          :unless => Proc.new {|m| m[:image].nil?}

  def rating
    if self.votes.count > 0
      vote_sum = self.votes.all.inject(0) { |sum, vote| sum + vote.value }
      vote_sum / votes.count
    else
      0
    end
  end

  def email_subscribers
    self.subscribers.each do |sub|
      UserMailer.new_modification(sub.email, self.title, self.id).deliver
    end
  end

  private
  
    def recipe_params
      params.require(:recipe).permit(:title)
    end
end

WebProgramming/mixr/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe_votes_count = {}
    @recipe_avgs = {}
    dates = []
    @recipe.votes.each do |vote|
      date = vote.id.generation_time.to_date
      if !@recipe_avgs[date]
        dates << date
        @recipe_votes_count[date] = 1
        @recipe_avgs[date] = vote.value
      else
        @recipe_votes_count[date] += 1
        @recipe_avgs[date] += vote.value
      end
    end

    dates.each do |date|
      @recipe_avgs[date] = @recipe_avgs[date] / @recipe_votes_count[date]
    end

    @modifications = []
    @recipe.recipe_ingredients.each do |r_ingr|
      r_ingr.modifications.each do |mod|
        @modifications << mod
      end
    end

    @recipe.steps.each do |step|
      step.modifications.each do |step|
        @modifications << step
      end
    end

    set_cookies
    parsed_cookies = JSON.parse(cookies[:recipes_viewed])
    @recently_viewed = []
    parsed_cookies.each do |r_cookie|
      r = Recipe.where(id: r_cookie["id"]["$oid"])
      if r.empty?
        next
      end
      r = r.first
      next if r == @recipe
      @recently_viewed << r
    end
  end

  def new
    @recipe = Recipe.new
    3.times { @recipe.recipe_ingredients.build }
    3.times { @recipe.steps.build }
  end

  def edit
  end

  def create
    @recipe = Recipe.new(title: params[:recipe][:title], image: params[:recipe][:image])
    recipe_ingredient_params = params[:recipe][:recipe_ingredients_attributes]
    steps_params = params[:recipe][:steps_attributes]

    respond_to do |format|
      if @recipe.save
        recipe_ingredient_params.each do |recipe_ingr|
          quantity = recipe_ingr[1][:quantity]
          ingr = recipe_ingr[1][:ingredient]

          next unless (quantity and !quantity.blank?) or (ingr and !ingr.blank?)

          ingr_name = recipe_ingr[1][:ingredient].downcase
          ingredient = Ingredient.where(name: ingr_name).first
          ingredient = ingredient || Ingredient.create(name: ingr_name)
          @recipe.recipe_ingredients.create(quantity: quantity, 
                                            ingredient: ingredient)
        end

        steps_params.each do |s|
          step = s[1]
          instr =  step[:instruction]
          next unless instr
          @recipe.steps.create(instruction: instr)
        end

        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(:title, :image)
    end

    def set_cookies
      to_add = { id: @recipe.id, time: Time.now }
      if cookies[:recipes_viewed] == nil
        parsed_cookies = nil
      else
        parsed_cookies = JSON.parse(cookies[:recipes_viewed])
      end

      if parsed_cookies == nil or parsed_cookies.empty?
        parsed_cookies = [to_add]
        cookies[:recipes_viewed] = JSON.generate(parsed_cookies)
      elsif !parsed_cookies.select{ |e| e["id"] == JSON.parse(JSON.generate(to_add[:id])) }.empty?
        return
      elsif parsed_cookies.length < 6
        parsed_cookies << to_add
        cookies[:recipes_viewed] = JSON.generate(parsed_cookies)
      else
        parsed_cookies = parsed_cookies.sort do |x,y| 
          x[:time] <=> y[:time]
        end

        parsed_cookies[parsed_cookies.length - 1] = to_add
        cookies[:recipes_viewed] = JSON.generate(parsed_cookies)
      end
    end
end

WebProgramming/mixr/app/helpers/recipes_helper.rb
module RecipesHelper
end

WebProgramming/mixr/app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
    <% if @recipe.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

            <ul>
            <% @recipe.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
            </ul>
        </div>
    <% end %>

    <div class="title-area">
        <h4>Recipe Title</h4>
        <%= f.text_field :title %>
    </div>

    <div class="ingredients">
        <h4>Ingredients</h4>
        <% quantity_placeholder = "e.g. 1 cup" %>
        <% ingr_placeholder = "e.g. flour" %>
        <%= f.fields_for :recipe_ingredients do |ingredient_form| %>
            <div class="field ingredients-field">
                <div>
                    <%= ingredient_form.label :quantity %>
                    <%= ingredient_form.text_field :quantity, placeholder: quantity_placeholder%>
                </div>
                <div>
                    <%= ingredient_form.label :ingredient %>
                    <%= ingredient_form.text_field :ingredient, placeholder: ingr_placeholder %>
                </div>
                <% quantity_placeholder = "" %>
                <% ingr_placeholder = "" %>
            </div>
        <% end %>
    </div>

    <%= link_to "Add another ingredient", "#Ingredients", id: "add-ingredient", class: "btn btn-primary" %>

    <% index = 1 %>
    <div class="steps">
        <h4>Directions</h4>
        <%= f.fields_for :steps do |step_form| %>
            <div class="field steps-field">
                <div><%= step_form.label "#{index}" %></div>
                <%= step_form.text_area :instruction, class: "directions-field" if index != 1%>
                <%= step_form.text_area :instruction, placeholder: "e.g. Add flour and milk together.", class: "directions-field" if index == 1%>
            </div>
            <% index += 1 %>
        <% end %>
    </div>

    <%= link_to "Add another step", "#Directions", id: "add-step", class: "btn btn-primary" %>


    <div>
        <h4>Image</h4>
        <div class="well" id="add-image-area"><%= f.file_field :image %></div>
    </div>

    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

WebProgramming/mixr/app/views/recipes/_modifications.html.erb
<span class="mods">
  <i class="fa fa-comment mod-toggle"></i>
  <span class="suggestions">
    <ul>
      <% modifications.each do |mod| %>
        <li>
        <div class="ratebox" data-id=<%= mod.id %> id=<%= mod.id %> data-rating=<%= mod.rating %>></div>
          <%= mod.suggestion %>
        </li>
      <% end %>
      <li>
        <span class="new-mod-form">
          <%= form_tag modifications_path do %>
            <%= text_area_tag 'new_mod', nil, placeholder: "Submit a new modification.", class: "new-mod", id: orig_id %>
            <%= submit_tag 'Submit', class: "submit-mod btn btn-primary"%>
          <% end %>
        </span>
      </li>
    </ul>
  </span>
</span>

WebProgramming/mixr/app/views/recipes/new.html.erb
<% provide(:title, "New Recipe") %>
<h1>New Recipe</h1>

<div class = "form">
  <%= render 'form' %>
</div>

WebProgramming/mixr/app/views/recipes/show.html.erb
<% provide(:title, @recipe.title) %>

<div id="wrapper">
    <!-- Sidebar -->
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <h4 class="sidebar-brand">
                Modifications
            </h4>

            <% @recipe.recipe_ingredients.each do |r_ingr| %>
                <div class="suggestions" id=<%= "orig-mods-" + r_ingr.id %>>
                    <h5 class="mod-subtitle">
                        <%= r_ingr.ingredient.name.upcase if r_ingr and r_ingr.ingredient %>
                    </h5>
                    <div class="well suggestion-well">
                        <% r_ingr.modifications.each_with_index do |mod, index| %>
                            <li class="single-suggestion">
                                <div class="ratebox suggestion-rating" data-id=<%= mod.id %> id=<%= mod.id %> data-rating=<%= mod.rating %>></div>
                                <p><%= mod.suggestion %></p>
                                <% if index < r_ingr.modifications.length - 1 %>
                                    <hr class="mod-separator"/>
                                <% end %>
                            </li>
                        <% end %>
                        <span class="new-mod-form">
                            <%= form_tag modifications_path do %>
                                <%= text_area_tag 'new_mod', nil, placeholder: "Submit a new modification.", class: "new-mod", id: r_ingr.id %>
                                <%= submit_tag 'Submit', class: "submit-mod btn btn-default"%>
                            <% end %>
                        </span>
                    </div>
                </div>
            <% end %>

            <% @recipe.steps.each do |step| %>
                <div class="suggestions" id=<%= "orig-mods-" + step.id %>>
                    <h5 class="mod-subtitle">
                        <% if step.instruction %>
                            <% label =    step.instruction[0..25] %>
                            <% label = label == step.instruction ? label : label + " ..." %>
                            <%= label.upcase %>
                        <% end %>
                    </h5>
                    <div class="well suggestion-well">
                        <% step.modifications.each_with_index do |mod, index| %>
                            <li class="single-suggestion">
                                <div class="ratebox" data-id=<%= mod.id %> id=<%= mod.id %> data-rating=<%= mod.rating %>></div>
                                <p><%= mod.suggestion %></p>
                                <% if index < step.modifications.length - 1 %>
                                    <hr class="mod-separator"/>
                                <% end %>
                            </li>
                        <% end %>
                    </div>
                    <span class="new-mod-form">
                        <%= form_tag modifications_path do %>
                            <%= text_area_tag 'new_mod', nil, placeholder: "Submit a new modification.", class: "new-mod", id: step.id %>
                            <%= submit_tag 'Submit', class: "submit-mod btn btn-default"%>
                        <% end %>
                    </span>
                </div>
            <% end %>
        </ul>
    </div>
    <!-- /#sidebar-wrapper -->


    <!-- Page Content -->
    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
 
                    <h1><%= @recipe.title %></h1>
                    <div class="ratebox recipe-rating"
                             data-id=<%= @recipe.id %>
                             id=<%= @recipe.id %>
                             data-rating=<%= @recipe.rating %>
                             >
                    </div> 
                    <%= image_tag @recipe.image.url, class: "recipe-img" if @recipe.image?%>
                    <div class="recipe-contents">
                        <h4 class="subtitle">Ingredients</h4>
                        <ul class="recipe-ingredients">
                            <% @recipe.recipe_ingredients.each do |r_ingr| %>
                                <% next unless r_ingr and r_ingr.ingredient %>
                                <li>
                                    <i class="fa fa-comment mod-toggle" id=<%= "orig-id-" + r_ingr.id %>></i>
                                    <span class="italic"><%= r_ingr.quantity %></span>
                                    <span class="bold"><%= r_ingr.ingredient.name if r_ingr and r_ingr.ingredient %></span>
                                </li>
                            <% end %>
                        </ul>
                        <h4 class="subtitle">Directions</h4>
                        <ol class="steps">
                            <% @recipe.steps.each do |step| %>
                                <li>
                                    <i class="fa fa-comment mod-toggle" id=<%= "orig-id-" + step.id %>></i>
                                    <%= step.instruction %>
                                </li>
                            <% end %>
                        </ol>
                    </div>
                    <div id="share_button" class="share-btn-span" 
                            recipe-id=<%= @recipe.id %> recipe-title='<%= @recipe.title %>' 
                            image-url='<%= @recipe.image? ? URI.join(request.url, @recipe.image.url) : "nil" %>'>

                        <div class="fb-share-button" data-href="https://fathomless-eyrie-3707.herokuapp.com/recipes/<%= @recipe.id %>" data-layout="button"></div>
                    </div>

                    <div>
                        <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Show/Hide Modifications Bar</a>
                    </div>
                    <div>
                        <a href="#stats-toggle" class="btn btn-default" id="stats-toggle">Show/Hide Recipe Stats</a>
                    </div>

                    <span id="chart">
                        <div class= "chart">
                            <%= line_chart [{data: @recipe_votes_count }], min: Time.now - 5.days, max: Time.now %>
                        </div>
                        <h4 class="chart-label"> Number of Votes Per Day</h4>
                    </span>
                </div>
            </div>
        </div>
    </div>
    <!-- /#page-content-wrapper -->
    <div id ="right-sidebar" class="no-mobile">
        <br><br>
        <div class="well subscriber-box">
            <div>
                <p>Want to be notified when new modifications are added to this recipe? Enter your email here.</p>
                <%= text_field_tag "add-subscriber", "", id: "add-subscriber" %>
                <%= submit_tag "Submit", class: "submit-sub", id: "r" + @recipe.id %>
            </div>
        </div>

        <% if @recently_viewed != nil and !@recently_viewed.empty? %> 
            <h3>You recently viewed:</h3>
            <% @recently_viewed.each do |viewed| %>
                <h5 class="recent-links"><%= link_to viewed.title, viewed %></h5>
            <% end %>
        <% end %>
    </div>

</div>



<!-- /#wrapper -->


<!-- Menu Toggle Script -->
<script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    $("#stats-toggle").click(function(e) {
        e.preventDefault();
        $("#chart").toggle("show");
    });
</script>