WebProgramming/mixr/config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :modifications
  resources :votes
  resources :subscribers

  get 'search', to: 'search#search'
  get 'welcome/index'
  root 'welcome#index'
end

WebProgramming/mixr/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title><%= full_title(yield(:title)) %></title>

    <link href='//fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700' rel='stylesheet' type='text/css'>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <%= csrf_meta_tags %>
</head>


<body>
    <div id="fb-root"></div>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">MIXR</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <%=form_tag("/search", method: :get, class: "navbar-form navbar-left" ) do%>
                    <%=text_field_tag "search", nil, class:"form-control search-bar", placeholder: "Search for recipes" %>
                    <%= button_tag(type: "Submit", class: "btn btn-default") do %>
                        <i class="fa fa-search"></i>
                    <% end %> 		
                <% end%>
                <ul class="nav navbar-nav navbar-right navbar-static-top">
                    <li class ="loggedin"><%= link_to 'Add recipe', new_recipe_path %></li>
                    <li class = "loggedin"> &nbsp; </li>
                    <li class="fb-btn"><fb:login-button scope="public_profile,email" data-auto-logout-link="true" onlogin="checkLoginState();"></fb:login-button></li>
                </ul>

            </div><!--/.nav-collapse -->
        </div>
    </nav>

    <div class="container">

        <div class="starter-template">
            <% flash.each do |message_type, message| %>
                <div class="alert alert-<%= message_type %>"><%= message %></div>
            <% end %>
            <%= yield %>
        </div>
    </div><!-- /.container -->

</body>

</html>